### ISSUE TITLE
Omega Flowey fight crash

### ISSUE THREAD

**Issue by crumblingstatue** [crumblingstatue/FloweysTimeMachine#17]
https://www.reddit.com/r/Undertale/comments/3oq6zc/floweys_time_machine/cwsrfdi?context=3

**Comment by fjay69** [comment]
Hello. After defeating Omega Flowey game is crashing. Reboot does not help.

**Comment by crumblingstatue** [comment]
I decided that trying to make sure that every possible output cannot break the game would be pretty much impossible.

Always make a backup if you value your existing save file.

**Comment by jD91mZM2** [comment]
The game crashes because it couldn't find file8. Duplicate your 'file0' and rename it to 'file8'. This is not related to Flowey's Time Machine itself.
