### ISSUE TITLE
Time Machine, resetting Mettaton to "initial state" doesn't work?

### ISSUE THREAD

**Issue by crumblingstatue** [crumblingstatue/FloweysTimeMachine#18]
from Fynriel

> I accidently killed him before killing everyone else in that region now my Genocide run is screwed. But I can't seem to be able to actually reset him with your time machine. Every other change totally works.

**Comment by rma1994** [comment]
You need to change the "'Plot' value" to "Hotlands Genocide".
This will do the trick ;)

**Comment by jD91mZM2** [comment]
Um... @crumblingstatue... Time to close the issue? :P
