### ISSUE TITLE
Playing Fetch with Greater Dog to spare sets Greater Dog to 2

### ISSUE THREAD

**Issue by DoomRater** [crumblingstatue/FloweysTimeMachine#22]
I am willing to bet ALL the dogs have a flag for having been beaten by playing fetch with them.

**Comment by ghost** [comment]
Can confirm, the same happens for Lesser Dog, Doggo, and Dogamy & Dogaressa.

While we're on the subject of the unknowns for the dogs (or any monster really), they're simply the alternate ways to end the fight: the wiki should list all battle outcome possibilities.

**Comment by noirscape** [comment]
I suppose it's because beating the Dogs by playing fetch with them activates the yellow text in the ending.

**Comment by jD91mZM2** [comment]
Also noted in http://rawr.ws/undertale/flags

![image](https://cloud.githubusercontent.com/assets/12830969/24547512/8157af9a-1610-11e7-88a6-32752554612b.png)
