### ISSUE TITLE
"Spared" State for Papyrus is missing

### ISSUE THREAD

**Issue by kinker31** [crumblingstatue/FloweysTimeMachine#23]
This was discovered after I set my save location to the Waterfall checkpoint. When I went back into the Snowdin Town, the battle dialogue for Papyrus initiated, and thus, the battle for Papyrus began.

**Comment by crumblingstatue** [comment]
Interestingly, if I spare papyrus, his state stays at "Initial State".

There is probably some other variable that controls whether you battled him or not.

**Comment by crumblingstatue** [comment]
Apparently line 543 changes from 2 to 101 after you fight Papyrus.

Not sure what to name this variable.

**Comment by crumblingstatue** [comment]
Alright, now you can set whether you fought Papyrus or not under "Papyrus fight state".

**Comment by kinker31** [comment]
Thanks.
