### ISSUE TITLE
Line 543 (sav-plotvalue)

### ISSUE THREAD

**Issue by Yerningcross8** [crumblingstatue/FloweysTimeMachine#27]
Whenever I load a save it always says the number in line 543 is wrong, no matter what number it is. I cant seem to get the time machine to save over my own save unlike the  very first time i did it. I also have windows 7 if that helps

**Comment by Yerningcross8** [comment]
for example my current number is 17, and it says this "unknown value 17 for line 543

**Comment by crumblingstatue** [comment]
Should be fixed by 55fae22a2bdc5a09162985efb207f6266ea4c41b.
