### ISSUE TITLE
Toriel 3rd State

### ISSUE THREAD

**Issue by Coolway99** [crumblingstatue/FloweysTimeMachine#29]
The drop down menu for Toriel's State has Initial, Unknown, Killed, and Unknown. The first Unknown produces an error (resuming from flowey's corridor in the ruins with it set) and the second Unknown is Toriel has been spared. Thought that might help.

I would assume that perhaps the first Unknown is Toriel is waiting to fight you. Have not tested this yet

**Comment by jD91mZM2** [comment]
Interesting!

**Comment by jD91mZM2** [comment]
Made a pull request for you, [#46](https://github.com/crumblingstatue/FloweysTimeMachine/pull/46)
