### ISSUE TITLE
Undyne the Undying preset contains impossiblities

### ISSUE THREAD

**Issue by Samario1** [crumblingstatue/FloweysTimeMachine#35]
Apart from the PLOT value still being 'didn't fight Papyrus' and all the area killcounts being 99, you have the player with a Legendary Hero in their inventory, which cannot be obtained until the end of Hotland, going into the CORE, which is after Undying. You also do not have the cellphone, which is also impossible without skipping the cutscene where Toriel gives you the phone, and the Kill count is set to 999; apart from that not being what's used (??? kill count is used instead), there's no way to kill 999 monsters at that point in the game. The Sans Battle preset has the killcount for these areas correct, so you could lift the killcounts from there.

**Comment by crumblingstatue** [comment]
I mainly made the boss fight presets just for the purpose of fighting the bosses. I didn't intend them to be faithful to legitimate saves.

That being said, I'm accepting pull requests fixing the "impossibilities".
