### ISSUE TITLE
Unknown value '202' for line 18

### ISSUE THREAD

**Issue by Fusionx963** [crumblingstatue/FloweysTimeMachine#37]
What does that mean? I get that error message even after I reinstalled this program. Here's what it looks like.
![flowey s error message](https://cloud.githubusercontent.com/assets/25549754/22618980/537aae16-eab8-11e6-9f05-5126126bc282.png)

**Comment by KockaAdmiralac** [comment]
You're talking about [my standalone fork](https://github.com/KockaAdmiralac/FloweysTimeMachine), right? I forgot to update the link in the alert, it should be posted [here](https://github.com/KockaAdmiralac/FloweysTimeMachine/issues) instead, sorry :/ Could you move it there?

I'm not maintaining the project much anymore but if that's a fatal bug I could look into fixing it

**Comment by jD91mZM2** [comment]
@Fusionx963 Please confirm this, so @crumblingstatue can close this issue.
