### ISSUE TITLE
True ending completed?

### ISSUE THREAD

**Issue by jD91mZM2** [crumblingstatue/FloweysTimeMachine#38]
Hi! Is there any way to mark that the true ending has been completed?

# In case it's not
I'd love for it to be a feature!  
Here is some information:

- file0 before and after: (Difference)[https://www.diffchecker.com/ffegx5UZ]
- It's for sure in file0, and not the INI or anything. I double checked.
- No changes are visible in the machine itself, AFAIK.
- http://rawr.ws/undertale/flags seems to have a few of these in flags. (Flag number + 31. For example 7 (true_pacifist) = 38, and line 38 now says "1" instead of "0")

Thanks! I would love a feature like this, and maybe even a preset :>  
You know, just to have a sorta open world undertale. Where you can walk around without story...

**Comment by Mnpn03** [comment]
Agreed!

**Comment by crumblingstatue** [comment]
I don't actively work on this project anymore, but if you'd like to implement this yourself, I accept pull requests.

**Comment by jD91mZM2** [comment]
Hmmm, maybe. I'll experiment some.  
EDIT: HA! Line 38 did the trick! Gonna make a pull request!

**Comment by jD91mZM2** [comment]
Pull request requested! Case closed. https://github.com/crumblingstatue/FloweysTimeMachine/pull/39
