### ISSUE TITLE
Completely unusable

### ISSUE THREAD

**Issue by brmbrmcar** [crumblingstatue/FloweysTimeMachine#55]
I don't really know what would be an appropriate title; change it if you wish.

So, I just come back to the machine, only to find:
![screenshot from 2017-04-01 20-05-38](https://cloud.githubusercontent.com/assets/14400196/24581608/9adf213a-1716-11e7-8fd9-d9710b3d1c50.png)
It cannot load files, or save. All menus are empty.
It seemed alright earlier today.

**Comment by crumblingstatue** [comment]
@LEGOlord208: <s>Maybe you can help shed some light on this. Maybe it's an issue with the new app cache?</s>

Please try using a syntax checker or linter like [JSHint](http://jshint.com/about/) before submitting your pull request. Of course this is also my fault as a maintainer for accepting code without testing it first.

**Comment by crumblingstatue** [comment]
Okay, this was caused by a syntax error in `main.js`. Should be fixed now.

**Comment by brmbrmcar** [comment]
Yay! It is fixed! Can we close this, or is it too soon?

**Comment by jD91mZM2** [comment]
Sorry :<

EDIT: I don't see how I missed this. I do have a local repo now, so I can test my things locally. Well, somehow I missed it. Again, sorry!  
Web isn't really my nature, so... :<
