### ISSUE TITLE
Ability to disable audio

### ISSUE THREAD

**Issue by brmbrmcar** [crumblingstatue/FloweysTimeMachine#56]
Flowey's laugh is just....

It could cause problems.

**Comment by crumblingstatue** [comment]
What kind of problems could it cause?

**Comment by Sixthhokage1** [comment]
@brmbrmcar I have a fork that disables audio, just finally merged upstream changes into it: https://github.com/Sixthhokage1/FloweysTimeMachine

@crumblingstatue Like screamers, it could trigger anxiety and panic attacks. It scared the everloving shit out of me when I first used the editor

**Comment by brmbrmcar** [comment]
If there is a whole fork for it, I can safely assume that this is a big issue.

**Comment by jD91mZM2** [comment]
....

You do know the sound is only once, right?  
And, you can just mute your computer audio.

**Comment by KockaAdmiralac** [comment]
To be honest this doesn't look like a huge issue to me. If Flowey's laugh is causing you issues, you can just mute the tab or your computer audio.

Unless somebody has enough time to implement a "mute audio" button.

**Comment by brmbrmcar** [comment]
But there is no warning for this. And I've been around computers where you can't change the audio at all. And in fact, if I can figure out how this thing works, I'll try go and do it!

**Comment by brmbrmcar** [comment]
Can someone check that https://github.com/brmbrmcar/FloweysTimeMachine works? I know the commits awfully messy....

**Comment by crumblingstatue** [comment]
I originally added the laugh because I thought it would go well with the theme of Undertale, where you are an evil bastard for toying around with the timelines.

But I suppose it can get annoying/problematic in some situations, so I'll accept an unobtrusive way to turn it off.
