### ISSUE TITLE
Adding Temmie Armour/Cowboy Hat does not increase attack

### ISSUE THREAD

**Issue by brmbrmcar** [crumblingstatue/FloweysTimeMachine#59]
It should. They both increase attack.

**Comment by jD91mZM2** [comment]
I *think* you're supposed to update it manually? Not sure

**Comment by crumblingstatue** [comment]
The defense values are automatically updated, so it would make sense to also automatically set attack when equipping an armor that has an attack bonus.

**Comment by KockaAdmiralac** [comment]
Fixed by #72.
