### ISSUE TITLE
Ugh? Who Hecks? 

### ISSUE THREAD

**Issue by Dobby233Liu** [crumblingstatue/FloweysTimeMachine#60]
I'm Use for Debug Mode or The TieBa Chinese Pack.
I'm Editing Mine Files, and Fast Go To "Snowdin - Town" of Waterfall. After Open Game and Read files, Frisk leave of Waterfall.

**Comment by Dobby233Liu** [comment]
I'TS NOT GO TO SNOWDIN

**Comment by jD91mZM2** [comment]
Did you edit both the INI and the save?

**Comment by Dobby233Liu** [comment]
Ugh no

**Comment by Dobby233Liu** [comment]
What the heck this been closed

**Comment by jD91mZM2** [comment]
Then edit both files, or use something like [UndertaleSandbox](https://github.com/legolord208/UndertaleSandbox) that does it for you.
