### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by ShinraTensei** [crumblingstatue/FloweysTimeMachine#61]
where you at bro

**Comment by crumblingstatue** [comment]
Csb

**Comment by ShinraTensei** [comment]
y u no irc

**Comment by crumblingstatue** [comment]
I am IRC? I'm on ##newboston.

**Comment by ShinraTensei** [comment]
i caym like 10 and dindu see you, vps is an herpo

**Comment by ShinraTensei** [comment]
like 10 times*

**Comment by crumblingstatue** [comment]
Well, now I am on, so stop being a faggot and talk to me on IRC instead of GitHub issues
