### ISSUE TITLE
Can I translate this repo to Chinese version?

### ISSUE THREAD

**Issue by chihuo2104** [crumblingstatue/FloweysTimeMachine#66]
I am a Chinese programmer.I like to play Undertale on Steam.Your save editor is useful.So,I want to translate to Chinese.Can I translate this repo to Chinese version?

**Comment by KockaAdmiralac** [comment]
I believe this was also mentioned in #64 (and #63) and there should already be a [Chinese (Simplified) version](https://floweys-time-machine-cn.mtrstatic.tk/) of Flowey's Time Machine.

**Comment by chihuo2104** [comment]
> I believe this was also mentioned in #64 (and #63) and there should already be a [Chinese (Simplified) version](https://floweys-time-machine-cn.mtrstatic.tk/) of Flowey's Time Machine.

Oh,I am late to have the question.Thanks!
