### ISSUE TITLE
file bugged

### ISSUE THREAD

**Issue by oscarstars12** [crumblingstatue/FloweysTimeMachine#69]
when I save the file and I load it and I changed it and I put it on undertale it shows the annoying dog and this is because the numbers are separated from the file

**Comment by KockaAdmiralac** [comment]
Can you provide the original save file(s) that you are editing with Flowey's Time Machine, explain which exact fields are you changing and provide the resulting file that's showing you the Annoying Dog screen?

**Comment by oscarstars12** [comment]
> Can you provide the original save file(s) that you are editing with Flowey's Time Machine, explain which exact fields are you changing and provide the resulting file that's showing you the Annoying Dog screen?
idk but I deleted the main one then put the one I made from floweys time machine and that happem

**Comment by KockaAdmiralac** [comment]
Can you provide the file that Flowey's Time Machine generated, then?

**Comment by byemc** [comment]
> when I save the file and I load it and I changed it and I put it on undertale it shows the annoying dog and this is because the numbers are separated from the file

You need to fill in some info, when loading SAVEs, FTM just forgets to include:
* LV
* Kills
* HP
* EXP
* Gold
* ATK
* DEF
* WP ATK
* ARM DEF
* Ruins/Snowdin/Waterfall/Hotlands(+ CORE) Kills (this only matters in genocide)

This is my SAVE, as seen by FTM.
![image](https://user-images.githubusercontent.com/77801870/121784428-d5b22480-cbab-11eb-99e5-91e866ff6320.png)

**Comment by KockaAdmiralac** [comment]
This should be fixed with https://github.com/crumblingstatue/FloweysTimeMachine/commit/8f655c18b2ac9500ada996ef61c7ee7fc1d74469. @ByeMC are you still experiencing the issue?

**Comment by byemc** [comment]
> This should be fixed with https://github.com/crumblingstatue/FloweysTimeMachine/commit/8f655c18b2ac9500ada996ef61c7ee7fc1d74469. @ByeMC are you still experiencing the issue?

Hi,

I'm not at my pc atm, I'll check with my old OMEGA FLOWEY save data later

**Comment by KockaAdmiralac** [comment]
I'm closing this issue as there has been no response in a month, please comment if you're still experiencing this so I can reopen the issue.

**Comment by byemc** [comment]
> I'm closing this issue as there has been no response in a month, please comment if you're still experiencing this so I can reopen the issue.

Sorry, forgot about it. Yes, it works perfectly now, thanks for fixing it!
